### ISSUE TITLE
replicated cell names in pseudotime vector

### ISSUE THREAD

**Issue by hernandezvargash** [Winnie09/Lamian#32]
Thanks for sharing this great package.
I managed to reproduce the vignette using the example datasets. However, I got stuck in Module3 (XDE test).
My trajectories have several branches and some cells may belong to more than one trajectory. This makes that my pseudotime vector has not the same length than my cell annotations.
This seems to trigger errors downstream, for example when plotting with plotXDEHm.
What is the best way to handle this multiple-trajectory scenario? Should each trajectory be analysed independently?
And then, how to best filter the trajectory structure to input the XDE test?
Thanks for your help,
Hector

**Comment by Winnie09** [comment]
Hi Hector,

Thanks for your interest in this package. The XDE test is designed for the analysis of **one** trajectory. Therefore, after you have a specific trajectory of interest, you can subset the cells in that trajectory for performing the XDE test. Hope this helps!

Wenpin

**Comment by hernandezvargash** [comment]
Thank you Wenpin!
I subset in each trajectory before XDE and it works now without errors.
