### ISSUE TITLE
TDE and XDE tests with pseudotime data from other tools 

### ISSUE THREAD

**Issue by pchiang5** [Winnie09/Lamian#7]
Hello,

Thank you for the tool.

Can I incorporate the outputs from other trajectory analyses into module 3 of Lamina?

For example, I have 2 trajectories (cluster 3 -> cluster 4 -> cluster 0 -> cluster 1 and cluster 3 -> cluster 4 -> cluster 2 -> cluster 5 -> cluster 7) with respective pseudotime data of from 1 sample. Is it reasonable to put the information into the 'design' parameter of the lamian.test() to compare the differential expression of the 2 trajectories?

**Comment by xzsword** [comment]
You can just turn the pseudotime into pseudotime rank and that will work. I checked the raw code and find the TSCAN pseudotime is the rank which is int. And it works for me (I used the slingshot)

**Comment by Winnie09** [comment]
Thanks for helping answer the question, @xzsword! That will work. 
@pchiang5  In the online manual, I added a new section "Apply other pseudotime inference methods in Lamian: take slingshot as an example" : https://winnie09.github.io/Wenpin_Hou/pages/Lamian.html#apply-other-pseudotime-inference-methods-in-lamian-take-slingshot-as-an-example

Please feel free to let me know if you have other questions!
